#!/usr/bin/env python3
"""Extract structured JSON from a filled BRRI Win2024 data collection form (.docx).

Usage:
  python extract_data_from_form.py path/to/form.docx
  python extract_data_from_form.py path/to/form.docx -o output.json

Works with forms generated by generate_data_collection_form.py.
After editing in Google Docs, download as .docx before extracting.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

try:
    from docx import Document
except ImportError:
    print("Install python-docx: backend/.venv/bin/pip install python-docx", file=sys.stderr)
    raise

SECTION_RE = re.compile(r"^SECTION:(\w+)\s*—")


def _cell_text(cell) -> str:
    return (cell.text or "").strip()


def _table_to_records(table, key_col: str = "field_key") -> list[dict[str, str]]:
    if not table.rows:
        return []
    headers = [_cell_text(c) for c in table.rows[0].cells]
    if key_col not in headers:
        return []
    records: list[dict[str, str]] = []
    for row in table.rows[1:]:
        values = [_cell_text(c) for c in row.cells]
        if len(values) < len(headers):
            values.extend([""] * (len(headers) - len(values)))
        rec = dict(zip(headers, values))
        if any(rec.get(h) for h in headers if h != key_col):
            records.append(rec)
    return records


def _table_to_kv(table) -> dict[str, str]:
    out: dict[str, str] = {}
    for row in table.rows[1:]:
        cells = row.cells
        if len(cells) < 3:
            continue
        key = _cell_text(cells[0])
        val = _cell_text(cells[2])
        if key:
            out[key] = val
    return out


def extract(doc_path: Path) -> dict:
    doc = Document(str(doc_path))
    result: dict = {
        "source_file": doc_path.name,
        "sections": {},
    }

    current_section: str | None = None
    body = doc.element.body

    from docx.oxml.text.paragraph import CT_P
    from docx.oxml.table import CT_Tbl
    from docx.table import Table
    from docx.text.paragraph import Paragraph

    for child in body.iterchildren():
        if isinstance(child, CT_P):
            para = Paragraph(child, doc)
            text = (para.text or "").strip()
            m = SECTION_RE.match(text)
            if m:
                current_section = m.group(1)
                if current_section not in result["sections"]:
                    result["sections"][current_section] = {
                        "title": text,
                        "kv": {},
                        "records": [],
                    }
        elif isinstance(child, CT_Tbl) and current_section:
            table = Table(child, doc)
            if not table.rows:
                continue
            headers = [_cell_text(c) for c in table.rows[0].cells]
            sec = result["sections"][current_section]
            if headers[:3] == ["field_key", "ক্ষেত্র", "মান"]:
                sec["kv"].update(_table_to_kv(table))
            elif "field_key" in headers:
                sec["records"].extend(_table_to_records(table))

    return result


def main() -> None:
    parser = argparse.ArgumentParser(description="Extract BRRI form data to JSON")
    parser.add_argument("docx", type=Path, help="Filled .docx file (download from Google Docs)")
    parser.add_argument("-o", "--output", type=Path, help="Output JSON path")
    args = parser.parse_args()

    if not args.docx.is_file():
        print(f"File not found: {args.docx}", file=sys.stderr)
        sys.exit(1)

    data = extract(args.docx)
    out = args.output or args.docx.with_suffix(".json")
    out.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Extracted → {out}")
    print(f"  Sections: {', '.join(data['sections'].keys())}")


if __name__ == "__main__":
    main()
